#!/usr/bin/env bash

cd "${0%/*}" || exit 1

# shellcheck disable=SC1091
. ../libbench

bench::test::as-variable() {
    a=1
    a=$((a+1))
}

bench::test::as-math-plus-plus() {
    a=1
    ((a++))
}

bench::test::as-math-plus-equals() {
    a=1
    ((a+=1))
}

bench::test::as-math-assignment() {
    a=1
    ((a=a+1))
}

bench::test::as-let-assign() {
    a=1
    # shellcheck disable=SC2219
    let "a=a+1"
}

bench::test::as-let-plus-plus() {
    a=1
    # shellcheck disable=SC2219
    let "a++"
}

bench::test::as-let-plus-equals() {
    a=1
    # shellcheck disable=SC2219
    let "a+=1"
}

bench::auto
