#!/usr/bin/env bash

cd "${0%/*}" || exit 1

# shellcheck disable=SC1091
. ../libbench

bench::test::arithmetic() {
    local i
    for ((i=0; i<1000; i++)); do
        :
    done
}

bench::test::brace-expansion() {
    local i
    for i in {1..1000}; do
        :
    done
}

bench::test::subshell-seq() {
    local i
    for i in $(seq 1 1000); do
        :
    done
}

bench::auto
