#!/usr/bin/env bash
cd "${0%/*}" || exit 1

# shellcheck disable=SC1091
. ../libbench

bench::test::shell-pwd() {
    local x
    x="$(cd ..; pwd)"
}

bench::test::shell-env() {
    local x
    x="$(cd ..; echo "$PWD")"
}

bench::test::env() {
    local oldPwd x
    oldPwd=$PWD
    cd ..
    x=$PWD
    # shellcheck disable=SC2164
    cd "$oldPwd"
}

bench::test::env-pwd() {
    local oldPwd x
    oldPwd=$PWD
    cd ..
    x=$(pwd)
    # shellcheck disable=SC2164
    cd "$oldPwd"
}

bench::test::pushd() {
    local x
    pushd .. &> /dev/null
    # shellcheck disable=SC2034
    x=$PWD
    # shellcheck disable=SC2164
    popd &> /dev/null
}

bench::auto
